Updates README.md
kubewarden/community pull request #6
Opened 2024-04-01 14:23 UTC by jvanz

## Description
Updates the README.md content adding the list of the repositories with their scope and status. The README.md file also has links to other useful documentation.

Related to https://github.com/kubewarden/kubewarden-controller/issues/659

**NOTE**: some links in this files requires other PR to be merge. However, we can merge it as it is. The link will work when all the PR got merged.

2024-04-01 14:31 UTC, robertsirc commented on README.md
> + - [Join the Community](#join-the-community)
where does this go?

2024-04-01 14:32 UTC, robertsirc approved these changes
This reads just fine. The only question is the link to join the community is that a CTA and where does that go?

2024-04-01 16:41 UTC, jvanz commented on README.md
> + - [Join the Community](#join-the-community)
To the other sections in the README file.

2024-04-01 16:43 UTC, jvanz commented on README.md
> + - [Join the Community](#join-the-community)
I just noticed that there are some broken links. I'll fix it.

2024-04-01 16:45 UTC, jvanz commented on README.md
> + - [Join the Community](#join-the-community)
Fixed.

2024-04-02 07:57 UTC, olblak commented on README.md
> +[mishi@linux.com](mailto:mishi@linux.com) to report an issue.
I am surprised that we need to specify a specific person address.
What if that person stop working for the LF?

2024-04-02 08:00 UTC, olblak approved these changes

2024-04-02 08:01 UTC, olblak commented on README.md
> +[mishi@linux.com](mailto:mishi@linux.com) to report an issue.
Just to clarify that my comment is not a blocker but just a notice. Feel free to close it if we can't use a "generic" email address

2024-04-03 20:07 UTC, jvanz commented on README.md
> +[mishi@linux.com](mailto:mishi@linux.com) to report an issue.
Good question, I was following the Falco example and just copy this paragraph. But you're right. I need to double check if I should do that.

2024-04-03 20:14 UTC, jvanz commented on README.md
> +[mishi@linux.com](mailto:mishi@linux.com) to report an issue.
Reading the CNCF documentation I found better information to use in this section. Therefore, I've updated the content. ;)

2024-04-04 09:11 UTC, viccuad commented on README.md
> +| [kubewarden/cel-policy](https://github.com/kubewarden/cel-policy)                                                                                                  | [![Stable](https://img.shields.i
I think the cel-policy repo should be in incubating status for now.

2024-04-04 09:16 UTC, viccuad approved these changes
LGTM, just status of cel-policy and kyverno policy.

2024-04-04 10:44 UTC, flavio requested changes

2024-04-04 10:44 UTC, flavio commented on README.md
> +| [kubewarden/helm-charts](https://github.com/kubewarden/helm-charts)                     | [![Stable](https://img.shields.io/badge/status-stable-brightgreen?style=for-the-badge)](https://github.com/
I've just put the most important repos (from a user POV) first, I've also done some small change to the policy-evaluator and policy-fetcher descriptions


```suggestion
| [kubewarden/kubewarden-controller](https://github.com/kubewarden/kubewarden-controller) | [![Stable](https://img.shields.io/badge/status-stable-brightgreen?style=for-the-badge)](https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#stable) |          Manage admission policies in your Kubernetes cluster with ease   |
| [kubewarden/policy-server](https://github.com/kubewarden/policy-server)                 | [![Stable](https://img.shields.io/badge/status-stable-brightgreen?style=for-the-badge)](https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#stable) |           Webhook server that evaluates WebAssembly policies to validate Kubernetes requests   |
| [kubewarden/audit-scanner](https://github.com/kubewarden/audit-scanner)                 | [![Stable](https://img.shields.io/badge/status-stable-brightgreen?style=for-the-badge)](https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#stable) |             Reports evaluation of existing Kubernetes resources with your already deployed Kubewarden policies|
| [kubewarden/kwctl](https://github.com/kubewarden/kwctl/)              | [![Stable](https://img.shields.io/badge/status-stable-brightgreen?style=for-the-badge)](https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#stable) |          Go-to CLI tool for Kubewarden users   |
| [kubewarden/helm-charts](https://github.com/kubewarden/helm-charts)                     | [![Stable](https://img.shields.io/badge/status-stable-brightgreen?style=for-the-badge)](https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#stable) |            Helm charts for the Kubewarden project   |
| [kubewarden/policy-evaluator](https://github.com/kubewarden/policy-evaluator)           | [![Stable](https://img.shields.io/badge/status-stable-brightgreen?style=for-the-badge)](https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#stable) |           Rust library used by Kubewarden to evaluate policies with a given input, request to evaluate and settings.   |
| [kubewarden/policy-fetcher](https://github.com/kubewarden/policy-fetcher/)              | [![Stable](https://img.shields.io/badge/status-stable-brightgreen?style=for-the-badge)](https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#stable) |             Rust library used by Kubewarden to pull policies from OCI registries and HTTP servers. |
```

2024-04-04 10:44 UTC, flavio commented on README.md
> +| [kubewarden/cel-policy](https://github.com/kubewarden/cel-policy)                                                                                                  | [![Stable](https://img.shields.i
Yes, I agree

2024-04-04 10:44 UTC, flavio commented on README.md
> +### Policies
I would do the following changes if possible:

* Put the repos in alphabetical order (if it's not too much, I hope you used a script to generate the table, maybe we could add a `status` label to the repos and build everything via script)
* Create a new section with the policy templates:
  * Go, Rust, OPA, Gatekeeper: stable
  * DotNet: incubation
  * Swift: sandbox

2024-04-04 10:44 UTC, flavio commented on README.md
> +| [kubewarden/policy-hub](https://github.com/kubewarden/policy-hub)                                                                                            | [![Stable](https://img.shields.io/badg
I've archived that

2024-04-04 10:44 UTC, flavio commented on README.md
> +| [kubewarden/hugo-gh-pages](https://github.com/kubewarden/hugo-gh-pages)                                                                           | [![Stable](https://img.shields.io/badge/status-st
This is archived, we might even drop it

2024-04-04 12:21 UTC, jvanz commented on README.md
> +| [kubewarden/cel-policy](https://github.com/kubewarden/cel-policy)                                                                                                  | [![Stable](https://img.shields.i
Yes, as I said during a daily, we should review the status. I've added the same status for all the policies to make my life easier during the table writing. :)

Thanks for doing that!

2024-04-04 17:33 UTC, jvanz commented
@kubewarden/kubewarden-documentation @kubewarden/kubewarden-developers I've added a new file to contain the security policy of the project.

2024-04-05 12:52 UTC, jhkrug approved these changes
lgtm

2024-04-08 13:55 UTC, flavio requested changes
Everything looks great. I've one final request: can you move the policy SDK repos to another dedicated section?

The page should have these section:
* ready to use policies
* policy SDKs
* policy templates

2024-04-08 14:04 UTC, flavio approved these changes
That's perfect :clap: :heart:

2024-04-08 14:05 UTC, merged